import type { MailAccount, MailMessage, ProviderDefinition } from './types'

export const providerDefinitions: ProviderDefinition[] = [
  {
    id: 'google',
    label: 'Google',
    description: 'Gmail / Google Workspace',
    accent: '#4285f4',
    icon: 'G',
    authUrl: 'https://myaccount.google.com/apppasswords',
    guide: ['打开 Google 账户安全设置', '开启两步验证后进入应用专用密码', '生成 MailGo 专用授权凭据'],
    requiresAuthCode: true,
  },
  {
    id: 'qq',
    label: 'QQ 邮箱',
    description: '支持多个 QQ 邮箱并行同步',
    accent: '#38a9f9',
    icon: 'Q',
    authUrl: 'https://mail.qq.com/',
    guide: ['打开 QQ 邮箱设置', '进入账户安全并开启 POP3/IMAP 服务', '生成授权码并复制到 MailGo'],
    requiresAuthCode: true,
  },
  {
    id: 'outlook',
    label: 'Outlook',
    description: 'Outlook.com / Microsoft 365',
    accent: '#2f80ed',
    icon: 'O',
    authUrl: 'https://account.live.com/proofs/manage',
    guide: ['打开 Microsoft 账户安全页面', '进入高级安全选项', '创建应用密码并返回 MailGo'],
    requiresAuthCode: true,
  },
  {
    id: 'other',
    label: '其他邮箱',
    description: '自定义 IMAP / SMTP 服务器',
    accent: '#a5aec7',
    icon: '@',
    authUrl: 'https://support.google.com/mail/answer/7126229',
    guide: ['准备邮箱服务商的 IMAP / SMTP 参数', '确认已开启第三方客户端服务', '输入邮箱地址与授权凭据'],
    requiresAuthCode: true,
  },
]

export const sampleAccounts: MailAccount[] = [
  {
    id: 'google-work',
    provider: 'google',
    label: 'Google',
    email: 'olivia.chen@gmail.com',
    unread: 7,
    accent: '#4285f4',
    status: 'synced',
    lastSync: '刚刚同步',
  },
  {
    id: 'qq-personal',
    provider: 'qq',
    label: 'QQ 邮箱',
    email: 'olivia_chen@qq.com',
    unread: 3,
    accent: '#43a5f5',
    status: 'synced',
    lastSync: '2 分钟前',
  },
  {
    id: 'outlook-projects',
    provider: 'outlook',
    label: 'Outlook',
    email: 'olivia.chen@outlook.com',
    unread: 2,
    accent: '#2489d8',
    status: 'offline',
    lastSync: '离线缓存 · 16:42',
  },
]

export const sampleMails: MailMessage[] = [
  {
    id: 'launch-plan',
    accountId: 'google-work',
    folder: 'inbox',
    from: 'james.wilson@acme.com',
    senderName: 'James Wilson',
    subject: 'Q3 launch plan — final review',
    preview: 'Hi Olivia, Please find attached the final version of the Q3 launch plan. Let me know if you have any questions…',
    timestamp: '10:24',
    dateGroup: '今天',
    unread: true,
    starred: true,
    accent: '#8b5cf6',
    avatar: 'JW',
    body: [
      'Hi Olivia,',
      'Please find attached the final version of the Q3 launch plan.',
      'Let me know if you have any questions or feedback before our stakeholder meeting tomorrow.',
      'Best regards,\nJames',
    ],
    attachments: [
      { id: 'launch-pdf', name: 'Q3_launch_plan_final.pdf', size: '1.8 MB', kind: 'pdf' },
      { id: 'budget-sheet', name: 'Q3_budget_overview.xlsx', size: '426 KB', kind: 'sheet' },
    ],
  },
  {
    id: 'budget-update',
    accountId: 'google-work',
    folder: 'inbox',
    from: 'sophia.carter@acme.com',
    senderName: 'Sophia Carter',
    subject: 'Re: Budget update',
    preview: 'Thanks for the update. Looks good to me.',
    timestamp: '09:15',
    dateGroup: '今天',
    unread: true,
    starred: false,
    accent: '#55b9f3',
    avatar: 'SC',
    body: ['Hi Olivia,', 'Thanks for the update. Looks good to me.\nSophia'],
  },
  {
    id: 'design-system',
    accountId: 'qq-personal',
    folder: 'inbox',
    category: 'social',
    from: 'liam.zhang@studio.io',
    senderName: 'Liam Zhang',
    subject: 'Design system v2.0',
    preview: 'Here are the latest components and token changes for review.',
    timestamp: '08:47',
    dateGroup: '今天',
    unread: true,
    starred: false,
    accent: '#39cc7a',
    avatar: 'LZ',
    body: ['Hi Olivia,', 'Here are the latest components and token changes for review.\nLiam'],
  },
  {
    id: 'research-summary',
    accountId: 'google-work',
    folder: 'inbox',
    from: 'emily.morris@acme.com',
    senderName: 'Emily Morris',
    subject: 'Market research summary',
    preview: 'Please review the attached document before Thursday.',
    timestamp: '昨天',
    dateGroup: '昨天',
    unread: false,
    starred: true,
    accent: '#f9a61a',
    avatar: 'EM',
    body: ['Hi Olivia,', 'Please review the attached document before Thursday.\nEmily'],
    attachments: [{ id: 'research', name: 'market_research.pdf', size: '2.4 MB', kind: 'pdf' }],
  },
  {
    id: 'team-offsite',
    accountId: 'outlook-projects',
    folder: 'inbox',
    from: 'david.turner@outlook.com',
    senderName: 'David Turner',
    subject: 'Team offsite — agenda',
    preview: 'Sharing the draft agenda for our offsite next month.',
    timestamp: '昨天',
    dateGroup: '昨天',
    unread: false,
    starred: false,
    accent: '#1bb9c9',
    avatar: 'DT',
    body: ['Hi team,', 'Sharing the draft agenda for our offsite next month.\nDavid'],
  },
  {
    id: 'apple-connect',
    accountId: 'google-work',
    folder: 'inbox',
    category: 'apple-connect',
    from: 'no_reply@apple.com',
    senderName: 'Apple',
    subject: 'Your Apple Account was used to sign in',
    preview: 'A new sign-in to your Apple Account was detected on a new device.',
    timestamp: '周一',
    dateGroup: '周一',
    unread: true,
    starred: false,
    accent: '#9aa4b7',
    avatar: '',
    body: ['Hello Olivia,', 'A new sign-in to your Apple Account was detected on a new device. If this was you, no action is needed.', 'Apple Support'],
    hasHtml: true,
  },
  {
    id: 'apple-ad',
    accountId: 'qq-personal',
    folder: 'inbox',
    category: 'apple-ads',
    from: 'news@apple.com',
    senderName: 'Apple',
    subject: 'Discover what is new this month',
    preview: 'Explore new features, products and services from Apple.',
    timestamp: '周一',
    dateGroup: '周一',
    unread: false,
    starred: false,
    accent: '#e96886',
    avatar: '',
    body: ['Discover what is new this month.', 'Manage your email preferences from Apple at any time.'],
    hasHtml: true,
  },
]

export const folderLabels = [
  { id: 'inbox' as const, label: '收件箱', icon: 'inbox', unread: 12 },
  { id: 'starred' as const, label: '星标', icon: 'star', unread: 0 },
  { id: 'sent' as const, label: '已发送', icon: 'send', unread: 0 },
  { id: 'drafts' as const, label: '草稿箱', icon: 'document', unread: 3 },
  { id: 'archive' as const, label: '归档', icon: 'archive', unread: 0 },
  { id: 'spam' as const, label: '垃圾邮件', icon: 'shield', unread: 4 },
  { id: 'trash' as const, label: '回收站', icon: 'trash', unread: 0 },
]
